name: write-headers

on:
    schedule:
    - cron: "33 9 * * *"
    workflow_dispatch:
    push:
        paths:
            - "src/**"

jobs:
    generate-headers:
        runs-on: ubuntu-latest
        steps:
            - name: perform checkout
              uses: actions/checkout@v6
            - name: set up Python
              uses: actions/setup-python@v6
            - name: install dependencies
              run: pip install .
            - name: generate header-docs
              run: python src/generate_tei_templates.py
            - name: commit header-docs
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                commit_message: "feat: generate TEI-XML header-docs"